swagger: "2.0"
info:
  title: slsTestApp API
  description: API description of slsTestApp.
  version: 1.0.0
host: api.example.com
basePath: /dev
schemes:
  - https
tags:
  - name: person
    description: About person API

produces:
  - application/json

consumes:
  - application/json

paths:
  /slsTestApp/v1/api/person:
    get:
      summary: Returns a person which matches id in path.
      description: Returns a person which matches id in path.
      tags:
        - person
      parameters:
        - name: personId
          in: path
          description: person id which you want to get.
          required: true
          type: "string"
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/producePersonModel"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        404:
          description: Not Found
          schema:
            $ref: "#/definitions/error"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
      x-amazon-apigateway-integration:
        type: aws_proxy
        responses:
          default:
            statusCode: "200"
        uri: "arn:aws:apigateway:ap-northeast-1:lambda:path/2015-03-31/functions/arn:aws:lambda:ap-northeast-1:{Please replace with your IAM Account ID here.}:function:slsTestApp-getPerson-dev/invocations"
        httpMethod: "POST"
        contentHandling: "CONVERT_TO_TEXT"
    # post:
    #   summary: Create a new person.
    #   description: Create a new person.
    #   tags:
    #     - person
    #   parameters:
    #     - in: body
    #       schema:
    #         $ref: "#/definitions/consumePersonModel"
    #       name: personModel
    #       description: person model which you want to create.
    #       required: true
    #   responses:
    #     200:
    #       description: OK
    #       schema:
    #         $ref: "#/definitions/producePersonModel"
    #     404:
    #       description: Not Found
    #       schema:
    #         $ref: "#/definitions/error"
    # put:
    #   summary: Update person which matche id in path.
    #   description: Update person which matche id in path.
    #   tags:
    #     - person
    #   parameters:
    #     - in: path
    #       name: personId
    #       description: person id which you want to update.
    #       required: true
    #       type: "string"
    #   responses:
    #     200:
    #       description: OK
    #       schema:
    #         $ref: "#/definitions/producePersonModel"
    #     404:
    #       description: Not Found
    #       schema:
    #         $ref: "#/definitions/error"
    # delete:
    #   summary: Delete person which matche id in path.
    #   description: Delete person which matche id in path.
    #   tags:
    #     - person
    #   parameters:
    #     - in: path
    #       name: personId
    #       description: person id which you want to delete.
    #       required: true
    #       type: "string"
    #   responses:
    #     200:
    #       description: OK
    #       schema:
    #         $ref: "#/definitions/producePersonModel"

definitions:
  consumePersonModel:
    type: object
    properties:
      name:
        type: "string"
      weight:
        type: "string"
      age:
        type: "string"
  producePersonModel:
    type: object
    properties:
      personId:
        type: "string"
      name:
        type: "string"
      weight:
        type: "string"
      age:
        type: "string"
  error:
    type: object
    properties:
      errorCode:
        type: "string"
      errorMessage:
        type: "string"
